name = "dinner-recommend"
main = "src/index.ts"
compatibility_date = "2025-06-05"

[[d1_databases]]
binding = "DB"
database_name = "dinner-recommend-db"
database_id = "24c3e9c4-70f3-4afa-bf26-961adab00e33"

[triggers]
crons = ["0 5 * * *"]